/** @type {Array<{
 *   id: string,
 *   severity: string,
 *   category: string,
 *   description: string,
 *   language: string,
 *   pattern: string,
 *   antiPattern: string|null,
 *   filePattern: string,
 *   exclude: string[],
 *   suggestion: string,
 *   fixable: boolean
 * }>}
 */
const rules = [
  {
    id: 'discarded-error-go',
    severity: 'high',
    category: 'error-handling',
    description: 'Error return value discarded with _ — prevents error propagation and hides failures',
    language: 'go',
    pattern: '_\\s*(?::=|=)\\s*\\w[\\w.]*\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.go',
    exclude: [
      '**/*_test.go',
      '**/vendor/**',
    ],
    suggestion: 'Handle all error return values. If an error is genuinely safe to ignore (e.g. close on a read-only resource), add a comment explaining why.',
    fixable: false,
  },
  {
    id: 'fmt-println-debug-go',
    severity: 'medium',
    category: 'debugging-leftovers',
    description: 'fmt.Print* used for debug output — should be replaced with structured logging',
    language: 'go',
    pattern: 'fmt\\.Print(?:ln|f)?\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.go',
    exclude: [
      '**/*_test.go',
      '**/vendor/**',
      '**/cmd/**',
      '**/main.go',
    ],
    suggestion: 'Replace fmt.Print* with a structured logger (slog, zap, logrus). fmt.Print* in non-main packages is almost always a debugging leftover.',
    fixable: false,
  },
  {
    id: 'spew-dump-debug-go',
    severity: 'high',
    category: 'debugging-leftovers',
    description: 'spew.Dump used for debug output — development-only dependency left in code',
    language: 'go',
    pattern: 'spew\\.(?:Dump|Sdump|Printf|Fprintf)\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.go',
    exclude: [
      '**/*_test.go',
      '**/vendor/**',
    ],
    suggestion: 'Remove spew.Dump calls. Use a structured logger or the debugger for inspection in development.',
    fixable: true,
  },
  {
    id: 'empty-error-handling-go',
    severity: 'high',
    category: 'error-handling',
    description: '`if err != nil { return nil }` — error is checked but returned as nil, hiding the failure',
    language: 'go',
    pattern: 'if\\s+err\\s*!=\\s*nil\\s*\\{\\s*return\\s+nil\\s*\\}',
    antiPattern: null,
    filePattern: '**/*.go',
    exclude: [
      '**/*_test.go',
      '**/vendor/**',
    ],
    suggestion: 'Return the error (or a wrapped version) instead of nil: `return fmt.Errorf("operation failed: %w", err)`. Returning nil when an error exists hides failures from callers.',
    fixable: false,
  },
  {
    id: 'ioutil-deprecated-go',
    severity: 'medium',
    category: 'deprecated-patterns',
    description: 'ioutil package usage — deprecated since Go 1.16, direct io/os replacements exist',
    language: 'go',
    pattern: 'ioutil\\.(?:ReadFile|WriteFile|ReadAll|ReadDir|TempDir|TempFile|NopCloser|Discard)',
    antiPattern: null,
    filePattern: '**/*.go',
    exclude: [
      '**/vendor/**',
    ],
    suggestion: 'Migrate to direct replacements: ioutil.ReadFile→os.ReadFile, ioutil.WriteFile→os.WriteFile, ioutil.ReadAll→io.ReadAll, ioutil.TempDir→os.MkdirTemp, ioutil.TempFile→os.CreateTemp.',
    fixable: true,
  },
];

export default rules;
