/** @type {Array<{
 *   id: string,
 *   severity: string,
 *   category: string,
 *   description: string,
 *   language: string,
 *   pattern: string,
 *   antiPattern: string|null,
 *   filePattern: string,
 *   exclude: string[],
 *   suggestion: string,
 *   fixable: boolean
 * }>}
 */
const rules = [
  {
    id: "discarded-error-go",
    severity: "high",
    category: "error-handling",
    description:
      "Error return value discarded with _ — prevents error propagation and hides failures",
    language: "go",
    pattern: "(?:,\\s*_|^\\s*_)\\s*(?::=|=)\\s*\\w[\\w.]*\\s*\\(",
    antiPattern:
      "defer\\s+\\w+\\.Close|_\\s*=\\s*\\w+\\.Close|_\\s*=\\s*fmt\\.|for\\s+_\\s*,|for\\s+.*,\\s*_\\s*:=\\s*range|_\\s*=\\s*\\w+\\.\\(|type\\s+_\\s",
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      "Handle all error return values. If an error is genuinely safe to ignore (e.g. close on a read-only resource), add a comment explaining why.",
    fixable: true,
  },
  {
    id: "fmt-println-debug-go",
    severity: "medium",
    category: "debugging-leftovers",
    description: "fmt.Print* used for debug output — should be replaced with structured logging",
    language: "go",
    pattern: "fmt\\.Print(?:ln|f)?\\s*\\(",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**", "**/cmd/**", "**/main.go"],
    suggestion:
      "Replace fmt.Print* with a structured logger (slog, zap, logrus). fmt.Print* in non-main packages is almost always a debugging leftover.",
    fixable: true,
  },
  {
    id: "spew-dump-debug-go",
    severity: "high",
    category: "debugging-leftovers",
    description: "spew.Dump used for debug output — development-only dependency left in code",
    language: "go",
    pattern: "spew\\.(?:Dump|Sdump|Printf|Fprintf)\\s*\\(",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      "Remove spew.Dump calls. Use a structured logger or the debugger for inspection in development.",
    fixable: true,
  },
  {
    id: "empty-error-handling-go",
    severity: "high",
    category: "error-handling",
    description:
      "`if err != nil { return nil }` — error is checked but returned as nil, hiding the failure",
    language: "go",
    pattern: "if\\s+err\\s*!=\\s*nil\\s*\\{\\s*return\\s+nil\\s*\\}",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      'Return the error (or a wrapped version) instead of nil: `return fmt.Errorf("operation failed: %w", err)`. Returning nil when an error exists hides failures from callers.',
    fixable: true,
  },
  {
    id: "ioutil-deprecated-go",
    severity: "medium",
    category: "deprecated-patterns",
    description: "ioutil package usage — deprecated since Go 1.16, direct io/os replacements exist",
    language: "go",
    pattern: "ioutil\\.(?:ReadFile|WriteFile|ReadAll|ReadDir|TempDir|TempFile|NopCloser|Discard)",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      "Migrate to direct replacements: ioutil.ReadFile→os.ReadFile, ioutil.WriteFile→os.WriteFile, ioutil.ReadAll→io.ReadAll, ioutil.TempDir→os.MkdirTemp, ioutil.TempFile→os.CreateTemp.",
    fixable: true,
  },
  {
    id: "bare-return-err-go",
    severity: "low",
    category: "error-handling",
    description:
      "`if err != nil { return err }` — error returned without wrapping loses call-site context",
    language: "go",
    pattern: "if\\s+err\\s*!=\\s*nil\\s*\\{\\s*return\\s+err\\s*\\}",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion: 'Wrap the error with context: return fmt.Errorf("operation failed: %w", err)',
    fixable: true,
  },
  {
    id: "log-println-debug-go",
    severity: "medium",
    category: "debugging-leftovers",
    description: "log.Print* used for debug output — should be replaced with structured logging",
    language: "go",
    pattern: "log\\.(?:Print|Println|Printf)\\s*\\(",
    antiPattern: "log/slog|go\\.uber\\.org/zap|sirupsen/logrus",
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**", "**/cmd/**"],
    suggestion: "Use structured logging instead of log.Print",
    fixable: true,
  },
  {
    id: "open-without-defer-close-go",
    severity: "high",
    category: "resource-management",
    description:
      "File or resource opened without a deferred Close — resource may leak on early return or panic",
    language: "go",
    pattern: "(?:\\.Open\\(|os\\.Create\\()",
    antiPattern: "defer\\s+\\w+\\.Close",
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      "Always defer Close immediately after a successful open: `f, err := os.Open(...); if err != nil { ... }; defer f.Close()`.",
    fixable: true,
  },
  {
    id: "goroutine-no-context-go",
    severity: "high",
    category: "concurrency",
    description: "Goroutine launched without context — may leak if the parent exits",
    language: "go",
    pattern: "go\\s+(?:func\\s*\\(|[a-zA-Z_]\\w*(?:\\.\\w+)?\\s*\\()",
    antiPattern: "context|ctx\\.Done|select\\s*\\{",
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      "Pass a context.Context to the goroutine and select on ctx.Done() to support cancellation.",
    fixable: true,
  },
  {
    id: "panic-in-handler-go",
    severity: "high",
    category: "error-handling",
    description: "panic() used instead of returning an error — crashes the entire program",
    language: "go",
    pattern: "\\bpanic\\s*\\(",
    antiPattern: "recover\\s*\\(",
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**", "**/main.go"],
    suggestion:
      "Return an error instead of panicking. Use panic only for truly unrecoverable situations, and always have a recover() in place.",
    fixable: true,
  },
  {
    id: "log-fatal-go",
    severity: "medium",
    category: "error-handling",
    description: "log.Fatal* calls os.Exit — should only be used in main()",
    language: "go",
    pattern: "log\\.Fatal(?:f|ln)?\\s*\\(",
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**", "**/main.go", "**/cmd/**"],
    suggestion:
      "Return an error to the caller instead of calling log.Fatal. log.Fatal calls os.Exit(1) which skips deferred functions.",
    fixable: true,
  },
  {
    id: "sql-string-concat-go",
    severity: "critical",
    category: "security",
    description: "SQL query built with string concatenation or fmt.Sprintf — SQL injection risk",
    language: "go",
    pattern:
      '(?:fmt\\.Sprintf\\s*\\(\\s*"(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\\b|"(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\\b[^"]*"\\s*\\+)',
    antiPattern: null,
    filePattern: "**/*.go",
    exclude: ["**/*_test.go", "**/vendor/**"],
    suggestion:
      'Use parameterized queries: db.Query("SELECT * FROM users WHERE id = $1", id) instead of string concatenation.',
    fixable: true,
  },
];

export default rules;
