/** @type {Array<{
 *   id: string,
 *   severity: string,
 *   category: string,
 *   description: string,
 *   language: string,
 *   pattern: string,
 *   antiPattern: string|null,
 *   filePattern: string,
 *   exclude: string[],
 *   suggestion: string,
 *   fixable: boolean
 * }>}
 */
const rules = [
  {
    id: 'bare-except-py',
    severity: 'high',
    category: 'error-handling',
    description: 'Bare `except:` or `except Exception: pass` — swallows all errors including KeyboardInterrupt and SystemExit',
    language: 'python',
    pattern: 'except\\s*(?:Exception\\s*(?:as\\s+\\w+\\s*)?)?:\\s*\\n\\s+(?:pass|print\\s*\\()',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
    ],
    suggestion: 'Catch specific exceptions and handle them explicitly. At minimum, log the error and re-raise. Never use bare `except:` as it catches SystemExit and KeyboardInterrupt.',
    fixable: false,
  },
  {
    id: 'print-debug-py',
    severity: 'medium',
    category: 'debugging-leftovers',
    description: 'print() used for debug output in non-CLI code',
    language: 'python',
    pattern: '^\\s*print\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
      '**/*cli*',
      '**/*command*',
      '**/__main__.py',
    ],
    suggestion: 'Replace print() with structured logging using the `logging` module. Use `logging.debug()` for debug output that can be filtered by log level.',
    fixable: false,
  },
  {
    id: 'pdb-debug-py',
    severity: 'critical',
    category: 'debugging-leftovers',
    description: 'pdb/ipdb debugger trace left in code — will pause execution in production',
    language: 'python',
    pattern: '(?:import\\s+pdb\\s*;\\s*pdb\\.set_trace\\(\\)|import\\s+ipdb\\s*;\\s*ipdb\\.set_trace\\(\\)|breakpoint\\s*\\(\\))',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
    ],
    suggestion: 'Remove all debugger breakpoints before committing. Use IDE breakpoints or conditional breakpoints in development instead.',
    fixable: true,
  },
  {
    id: 'open-without-context-manager-py',
    severity: 'high',
    category: 'resource-leaks',
    description: 'open() called without a `with` statement — file handle may not be closed on exception',
    language: 'python',
    pattern: '(?<!with\\s{0,10})(?<![\\w.])open\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
    ],
    suggestion: "Use a context manager: `with open('file.txt', 'r') as f:` — this guarantees the file is closed even if an exception occurs.",
    fixable: true,
  },
  {
    id: 'percent-string-format-py',
    severity: 'low',
    category: 'deprecated-patterns',
    description: 'Old-style % string formatting — use f-strings for clarity and performance',
    language: 'python',
    pattern: '"[^"]*%[sdifr][^"]*"\\s*%\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
      '**/migrations/**',
    ],
    suggestion: "Replace `'Hello %s' % name` with f-strings: `f'Hello {name}'`. F-strings are faster and less error-prone.",
    fixable: true,
  },
  {
    id: 'str-format-method-py',
    severity: 'low',
    category: 'deprecated-patterns',
    description: '.format() string formatting — prefer f-strings (Python 3.6+)',
    language: 'python',
    pattern: '"[^"]*\\{[^}]*\\}[^"]*"\\.format\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
      '**/migrations/**',
    ],
    suggestion: "Replace `'Hello {}'.format(name)` with f-strings: `f'Hello {name}'`. F-strings are more readable and performant.",
    fixable: true,
  },
  {
    id: 'os-path-instead-of-pathlib-py',
    severity: 'low',
    category: 'deprecated-patterns',
    description: 'os.path used instead of pathlib.Path — pathlib is the modern, object-oriented API',
    language: 'python',
    pattern: 'os\\.path\\.(?:join|exists|dirname|basename|splitext|abspath|expanduser|isfile|isdir)\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.py',
    exclude: [
      '**/*_test.py',
      '**/test_*.py',
      '**/tests/**',
    ],
    suggestion: 'Use pathlib.Path: os.path.join(a,b)→Path(a)/b, os.path.exists(p)→Path(p).exists(), os.path.dirname(p)→Path(p).parent, os.path.basename(p)→Path(p).name.',
    fixable: false,
  },
];

export default rules;
