/** @type {Array<{
 *   id: string,
 *   severity: string,
 *   category: string,
 *   description: string,
 *   language: string,
 *   pattern: string,
 *   antiPattern: string|null,
 *   filePattern: string,
 *   exclude: string[],
 *   suggestion: string,
 *   fixable: boolean
 * }>}
 */
const rules = [
  {
    id: 'empty-catch-ts',
    severity: 'high',
    category: 'error-handling',
    description: 'Empty catch block or catch block that only logs — errors are silently swallowed',
    language: 'typescript',
    pattern: 'catch\\s*\\([^)]*\\)\\s*\\{\\s*(?:console\\.(?:log|error|warn)\\([^)]*\\)\\s*;?\\s*)?\\}',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: 'Handle errors meaningfully: re-throw, wrap with context, or delegate to an error-handling utility. A logging-only catch is acceptable only when accompanied by a re-throw or explicit suppression comment.',
    fixable: false,
  },
  {
    id: 'console-log-debug-ts',
    severity: 'medium',
    category: 'debugging-leftovers',
    description: 'console.log / console.debug / console.info left in production code',
    language: 'typescript',
    pattern: 'console\\.(?:log|debug|info)\\s*\\(',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
      '**/*logger*',
      '**/*logging*',
    ],
    suggestion: 'Remove debug logs or replace with a structured logger (e.g. winston, pino) that can be disabled in production.',
    fixable: true,
  },
  {
    id: 'debugger-statement-ts',
    severity: 'high',
    category: 'debugging-leftovers',
    description: 'debugger statement left in source code',
    language: 'typescript',
    pattern: '\\bdebugger\\b\\s*;?',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: 'Remove the debugger statement before committing. Use breakpoints in your IDE instead.',
    fixable: true,
  },
  {
    id: 'full-lodash-import-ts',
    severity: 'medium',
    category: 'inefficient-imports',
    description: 'Full lodash library imported — causes large bundle size instead of tree-shaking individual functions',
    language: 'typescript',
    pattern: 'import\\s+(?:_|lodash)\\s+from\\s+[\'"]lodash[\'"]',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: "Import individual functions: `import { debounce } from 'lodash'` or use lodash-es for ESM tree-shaking.",
    fixable: true,
  },
  {
    id: 'full-rxjs-import-ts',
    severity: 'medium',
    category: 'inefficient-imports',
    description: 'Full RxJS library imported — prevents tree-shaking',
    language: 'typescript',
    pattern: 'import\\s+Rx\\s+from\\s+[\'"]rxjs[\'"]',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: "Import specific operators and classes: `import { Observable } from 'rxjs'` and `import { map } from 'rxjs/operators'`.",
    fixable: true,
  },
  {
    id: 'full-ramda-import-ts',
    severity: 'medium',
    category: 'inefficient-imports',
    description: 'Full Ramda library imported — causes large bundle size',
    language: 'typescript',
    pattern: 'import\\s+(?:R|ramda)\\s+from\\s+[\'"]ramda[\'"]',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: "Import individual functions: `import { map, filter } from 'ramda'`.",
    fixable: true,
  },
  {
    id: 'useeffect-missing-cleanup-ts',
    severity: 'high',
    category: 'resource-leaks',
    description: 'useEffect sets up a subscription, interval, or event listener without returning a cleanup function',
    language: 'typescript',
    pattern: 'useEffect\\s*\\(\\s*(?:async\\s*)?\\(\\s*\\)\\s*=>\\s*\\{[^}]*(?:setInterval|setTimeout|addEventListener|subscribe)[^}]*\\}\\s*,',
    antiPattern: 'return\\s*(?:\\(\\s*\\)|\\(\\)\\s*=>|function)',
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: 'Return a cleanup function from useEffect to prevent memory leaks: `return () => clearInterval(id)` / `return () => window.removeEventListener(...)` / `return () => subscription.unsubscribe()`.',
    fixable: false,
  },
  {
    id: 'promise-no-catch-ts',
    severity: 'high',
    category: 'error-handling',
    description: 'Promise chain (.then) without a .catch handler — unhandled rejections crash in Node.js and silently fail in browsers',
    language: 'typescript',
    pattern: '\\.then\\s*\\([^)]+\\)(?:\\s*\\.then\\s*\\([^)]+\\))*\\s*;',
    antiPattern: '\\.catch\\s*\\(',
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: 'Add a .catch() handler to the promise chain, or convert to async/await inside a try/catch block.',
    fixable: false,
  },
  {
    id: 'any-type-ts',
    severity: 'medium',
    category: 'type-safety',
    description: '`any` type used — disables TypeScript type checking for this value',
    language: 'typescript',
    pattern: '(?::\\s*any\\b|as\\s+any\\b|<any>|any\\[\\])',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/*.d.ts',
      '**/node_modules/**',
    ],
    suggestion: 'Replace `any` with a specific type, `unknown` (then narrow with type guards), or a generic parameter. If suppression is necessary, add a comment explaining why.',
    fixable: false,
  },
  {
    id: 'ts-ignore-comment-ts',
    severity: 'medium',
    category: 'type-safety',
    description: '@ts-ignore / @ts-expect-error / @ts-nocheck suppresses TypeScript errors without explanation',
    language: 'typescript',
    pattern: '//\\s*@ts-(?:ignore|expect-error|nocheck)',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/*.d.ts',
      '**/node_modules/**',
    ],
    suggestion: 'Resolve the underlying type error instead of suppressing it. If suppression is unavoidable, add an explanatory comment on the same line.',
    fixable: false,
  },
  {
    id: 'full-moment-import-ts',
    severity: 'medium',
    category: 'full-library-import',
    description: 'Full moment.js library imported — moment is large and largely superseded by date-fns or Temporal',
    language: 'typescript',
    pattern: 'import\\s+\\w+\\s+from\\s+[\'"]moment[\'"]',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: "Consider replacing moment.js with date-fns (tree-shakeable) or the native Temporal API. If moment is required, import only what you need.",
    fixable: true,
  },
  {
    id: 'full-underscore-import-ts',
    severity: 'medium',
    category: 'full-library-import',
    description: 'Full underscore.js library imported — causes large bundle size; prefer lodash-es or native equivalents',
    language: 'typescript',
    pattern: 'import\\s+_\\s+from\\s+[\'"]underscore[\'"]',
    antiPattern: null,
    filePattern: '**/*.{ts,tsx,js,jsx}',
    exclude: [
      '**/*.test.*',
      '**/*.spec.*',
      '**/node_modules/**',
    ],
    suggestion: "Replace underscore with native Array/Object methods or lodash-es for tree-shaking. If underscore is required, import individual functions.",
    fixable: true,
  },
];

export default rules;
