/** @type {Array<{
 *   id: string,
 *   severity: string,
 *   category: string,
 *   description: string,
 *   language: string,
 *   pattern: string,
 *   antiPattern: string|null,
 *   filePattern: string,
 *   exclude: string[],
 *   suggestion: string,
 *   fixable: boolean
 * }>}
 */
const rules = [
  {
    id: "empty-catch-ts",
    severity: "high",
    category: "error-handling",
    description: "Empty catch block — errors are silently swallowed",
    language: "typescript",
    pattern: "catch\\s*\\([^)]*\\)\\s*\\{\\s*\\}",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Handle errors meaningfully: re-throw, wrap with context, or delegate to an error-handling utility. A logging-only catch is acceptable only when accompanied by a re-throw or explicit suppression comment.",
    fixable: false,
  },
  {
    id: "catch-only-logs-ts",
    severity: "medium",
    category: "error-handling",
    description: "Catch block only logs the error without re-throwing or handling it",
    language: "typescript",
    pattern: "catch\\s*\\([^)]*\\)\\s*\\{\\s*console\\.(?:log|error|warn)",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Logging alone is not handling an error. Re-throw, wrap with context, or perform recovery; if suppression is intentional, add a comment explaining why.",
    fixable: false,
  },
  {
    id: "console-log-debug-ts",
    severity: "medium",
    category: "debugging-leftovers",
    description: "console.log / console.debug / console.info left in production code",
    language: "typescript",
    pattern: "console\\.(?:log|debug|info)\\s*\\(",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**", "**/*logger*", "**/*logging*"],
    suggestion:
      "Remove debug logs or replace with a structured logger (e.g. winston, pino) that can be disabled in production.",
    fixable: true,
  },
  {
    id: "debugger-statement-ts",
    severity: "high",
    category: "debugging-leftovers",
    description: "debugger statement left in source code",
    language: "typescript",
    pattern: "\\bdebugger\\b\\s*;?",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Remove the debugger statement before committing. Use breakpoints in your IDE instead.",
    fixable: true,
  },
  {
    id: "full-lodash-import-ts",
    severity: "medium",
    category: "inefficient-imports",
    description:
      "Full lodash library imported — causes large bundle size instead of tree-shaking individual functions",
    language: "typescript",
    pattern: "import\\s+\\w+\\s+from\\s+['\"]lodash['\"]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Import individual functions: import debounce from 'lodash/debounce' or use lodash-es for ESM tree-shaking: import { debounce } from 'lodash-es'.",
    fixable: true,
  },
  {
    id: "full-rxjs-import-ts",
    severity: "medium",
    category: "inefficient-imports",
    description: "Full RxJS library imported — prevents tree-shaking",
    language: "typescript",
    pattern: "import\\s+Rx\\s+from\\s+['\"]rxjs['\"]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Import specific operators and classes: `import { Observable } from 'rxjs'` and `import { map } from 'rxjs/operators'`.",
    fixable: true,
  },
  {
    id: "full-ramda-import-ts",
    severity: "medium",
    category: "inefficient-imports",
    description: "Full Ramda library imported — causes large bundle size",
    language: "typescript",
    pattern: "import\\s+(?:R|ramda)\\s+from\\s+['\"]ramda['\"]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion: "Import individual functions: `import { map, filter } from 'ramda'`.",
    fixable: true,
  },
  {
    id: "async-useeffect-ts",
    severity: "high",
    category: "react-hooks",
    description: "async function passed directly to useEffect — cleanup return value is lost",
    language: "typescript",
    pattern: "useEffect\\s*\\(\\s*async\\b",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Define the async function inside useEffect and call it: useEffect(() => { async function fetchData() { ... } fetchData(); return () => { /* cleanup */ }; }, [deps]);",
    fixable: false,
  },
  {
    id: "promise-no-catch-ts",
    severity: "high",
    category: "error-handling",
    description:
      "Promise chain (.then) without a .catch handler — unhandled rejections crash in Node.js and silently fail in browsers",
    language: "typescript",
    pattern: "\\.then\\s*\\(.*\\)\\s*;",
    antiPattern: "\\.catch\\s*\\(",
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Add a .catch() handler to the promise chain, or convert to async/await inside a try/catch block.",
    fixable: false,
  },
  {
    id: "any-type-ts",
    severity: "medium",
    category: "type-safety",
    description: "`any` type used — disables TypeScript type checking for this value",
    language: "typescript",
    pattern: "(?::\\s*any\\b|\\bas\\s+any\\b|<[^>]*\\bany\\b[^>]*>|any\\[\\])",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/*.d.ts", "**/node_modules/**"],
    suggestion:
      "Replace `any` with a specific type, `unknown` (then narrow with type guards), or a generic parameter. If suppression is necessary, add a comment explaining why.",
    fixable: false,
  },
  {
    id: "ts-ignore-comment-ts",
    severity: "medium",
    category: "type-safety",
    description:
      "@ts-ignore / @ts-expect-error / @ts-nocheck suppresses TypeScript errors without explanation",
    language: "typescript",
    pattern: "//\\s*@ts-(?:ignore|expect-error|nocheck)",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/*.d.ts", "**/node_modules/**"],
    suggestion:
      "Resolve the underlying type error instead of suppressing it. If suppression is unavoidable, add an explanatory comment on the same line.",
    fixable: false,
  },
  {
    id: "non-null-assertion-ts",
    severity: "medium",
    category: "type-safety",
    description: "Non-null assertion operator (!) bypasses TypeScript null checking",
    language: "typescript",
    pattern: "\\w+!\\.[\\w(]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/*.d.ts", "**/node_modules/**"],
    suggestion:
      "Use optional chaining (?.) or narrow the type with a type guard instead of asserting non-null with !.",
    fixable: false,
  },
  {
    id: "dangerously-set-inner-html-ts",
    severity: "high",
    category: "security",
    description:
      "dangerouslySetInnerHTML used — potential XSS vulnerability if content is not sanitized",
    language: "typescript",
    pattern: "dangerouslySetInnerHTML",
    antiPattern: "DOMPurify|sanitize|xss",
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Sanitize HTML content before rendering. Use a library like DOMPurify: dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(html) }}.",
    fixable: false,
  },
  {
    id: "full-moment-import-ts",
    severity: "medium",
    category: "full-library-import",
    description:
      "Full moment.js library imported — moment is large and largely superseded by date-fns or Temporal",
    language: "typescript",
    pattern: "import\\s+\\w+\\s+from\\s+['\"]moment['\"]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Consider replacing moment.js with date-fns (tree-shakeable) or the native Temporal API. If moment is required, import only what you need.",
    fixable: true,
  },
  {
    id: "full-underscore-import-ts",
    severity: "medium",
    category: "full-library-import",
    description:
      "Full underscore.js library imported — causes large bundle size; prefer lodash-es or native equivalents",
    language: "typescript",
    pattern: "import\\s+(?:_|underscore)\\s+from\\s+['\"]underscore['\"]",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**"],
    suggestion:
      "Replace underscore with native Array/Object methods or lodash-es for tree-shaking. If underscore is required, import individual functions.",
    fixable: true,
  },
  {
    id: "sql-string-concat-ts",
    severity: "critical",
    category: "security",
    description:
      "SQL query built via string concatenation or template literal — use parameterized queries",
    language: "typescript",
    pattern:
      '(?:"(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\\b[^"]*"\\s*\\+|\\+\\s*"[^"]*(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\\b|`[^`]*(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|ALTER)\\b[^`]*\\$\\{)',
    antiPattern: "(?:prepared|parameterized|placeholder|\\$\\d+|\\?)",
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: ["**/*.test.*", "**/*.spec.*", "**/node_modules/**", "**/*.d.ts"],
    suggestion:
      'Use parameterized queries (e.g., db.query("SELECT * FROM users WHERE id = $1", [id])) to prevent SQL injection.',
    fixable: false,
  },
  {
    id: "eval-usage-ts",
    severity: "critical",
    category: "security",
    description: "eval() or new Function() executes arbitrary code — use safer alternatives",
    language: "typescript",
    pattern: "(?:\\beval\\s*\\(|new\\s+Function\\s*\\()",
    antiPattern: null,
    filePattern: "**/*.{ts,tsx,js,jsx}",
    exclude: [
      "**/*.test.*",
      "**/*.spec.*",
      "**/node_modules/**",
      "**/*.d.ts",
      "**/webpack.config.*",
      "**/rollup.config.*",
      "**/vite.config.*",
    ],
    suggestion:
      "Replace eval() with JSON.parse() for data, or a proper parser/interpreter for expressions. new Function() has the same risks as eval().",
    fixable: false,
  },
];

export default rules;
