// Entry-point filenames that should never be flagged as dead code
export const ENTRY_POINT_NAMES = new Set([
  // Generic
  "index.js",
  "index.ts",
  "index.jsx",
  "index.tsx",
  "main.js",
  "main.ts",
  "main.go",
  "app.js",
  "app.ts",
  "server.js",
  "server.ts",
  "__init__.py",
  "__main__.py",
  "Program.cs",
  "Main.java",
  // Next.js App Router conventional files
  "page.js",
  "page.ts",
  "page.jsx",
  "page.tsx",
  "layout.js",
  "layout.ts",
  "layout.jsx",
  "layout.tsx",
  "loading.js",
  "loading.ts",
  "loading.jsx",
  "loading.tsx",
  "error.js",
  "error.ts",
  "error.jsx",
  "error.tsx",
  "not-found.js",
  "not-found.ts",
  "not-found.jsx",
  "not-found.tsx",
  "route.js",
  "route.ts",
  "middleware.js",
  "middleware.ts",
  "template.js",
  "template.ts",
  "template.jsx",
  "template.tsx",
  // Nuxt
  "app.vue",
  // Remix
  "root.tsx",
  "root.jsx",
  "entry.client.tsx",
  "entry.server.tsx",
  // SvelteKit
  "+page.svelte",
  "+layout.svelte",
  "+server.ts",
  "+server.js",
  // CLI / bin
  "cli.js",
  "cli.ts",
  "bin.js",
  "bin.ts",
  // Deno-style
  "mod.ts",
  "mod.js",
  // Python tooling
  "setup.py",
  "setup.cfg",
  "conftest.py",
  // Next.js Pages Router
  "_app.tsx",
  "_app.ts",
  "_app.jsx",
  "_app.js",
  "_document.tsx",
  "_document.ts",
  "_document.jsx",
  "_document.js",
  "_error.tsx",
  "_error.ts",
  "_error.jsx",
  "_error.js",
  // Django
  "manage.py",
  // Python WSGI/ASGI
  "wsgi.py",
  "asgi.py",
  // .NET / Java
  "Startup.cs",
  "Application.java",
  // Next.js App Router — additional conventional files
  "global-error.tsx",
  "global-error.ts",
  "global-error.jsx",
  "global-error.js",
  "default.tsx",
  "default.ts",
  "default.jsx",
  "default.js",
  "instrumentation.ts",
  "instrumentation.js",
  "opengraph-image.tsx",
  "opengraph-image.ts",
  "opengraph-image.js",
  "twitter-image.tsx",
  "twitter-image.ts",
  "twitter-image.js",
  "sitemap.ts",
  "sitemap.js",
  "robots.ts",
  "robots.js",
  "manifest.ts",
  "manifest.js",
]);

// Glob-style patterns for test files
export const TEST_FILE_PATTERNS = [
  /\.test\.[jt]sx?$/,
  /\.spec\.[jt]sx?$/,
  /_test\.go$/,
  /test_.*\.py$/,
  /.*_test\.py$/,
  /.*Test\.java$/,
  /.*Tests\.java$/,
  /.*Tests\.cs$/,
];
